title: MUDE Workbook 2026
author: MUDE Teachers and the Student Army from Delft University of Technology, built with <a href="https://teachbooks.io">TeachBooks</a> and <a href="https://jupyterbook.org/">Jupyter Book</a>, <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="license noopener noreferrer"">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt=""></a> #add your own name here

execute:
  execute_notebooks: "off"

only_build_toc_files: true

html:
  baseurl :  "https://mude.citg.tudelft.nl/workbook-2026" #BUMPBUMP

sphinx:
  config:
    html_theme_options:
      logo:
        text: Workbook 2026
        link: "https://mude.citg.tudelft.nl/"
        image_light: MUDE_Logo-small.png
        image_dark: MUDE_Logo-small.png
      repository_url: "https://github.com/TUDelft-MUDE/workbook-2026"
      path_to_docs: "book"
      repository_branch: "release"
      use_repository_button: true
      use_issues_button : true
    html_show_copyright: false
    html_last_updated_fmt: ''
    html_static_path: ["figures"] # add folders that contain files that need to be included, such as the location of the logo(s)
    mathjax3_config:
      chtml: {
        mtextInheritFont: true # To typeset text within math prettier
      }
    tud_change_logo: false
    tud_change_titlesize: false
    named_colors_custom_colors: {'attributiongrey':[150,150,150]}
  extra_extensions:
    - sphinx.ext.imgconverter
    - sphinx.ext.extlinks
    - teachbooks_favourites
    - sphinx_tudelft_theme

teachbooks:
  attribution_color: attributiongrey
  attribution_location: margin

bibtex_bibfiles: 
  - references.bib
